### ISSUE TITLE
update README

### ISSUE THREAD

**Issue by baqermarani** [baqermarani/OnlineFood_Project#4]
I Wanna update readme file but I can not create link for Design and Analysis ;
can you help me ?

**Comment by mohamadreza1999** [comment]
Hi man
I explain my idea in Pull request ('Baqermarani issues 1')
check it!

**Comment by mohamadreza1999** [comment]
I apply changes in it, now you can Update README.md

**Comment by baqermarani** [comment]
thanks bro
i will close this issue
